TopHundred/Controllers/IcosListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TopHundred.Entities;

namespace TopHundred.Controllers
{
    public class IcosListController : Controller
    {
        private readonly IcoListContext _context;
        private SignInManager<Customer> _signInManager;
        private readonly UserManager<Customer> _userManager;
        public IcosListController(IcoListContext context, SignInManager<Customer> signInManager, UserManager<Customer> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var items = await _context.IcoItems.Include(a => a.ListPosition).OrderBy(a => a.ListPosition.PositionValue)
                .ToListAsync();
            return View(items);
        }
        [HttpGet("icos/{id}")]
        public IActionResult IcoDetail(Guid id)
        {
            var item = _context.IcoItems.Include(a => a.ListPosition).FirstOrDefault(a => a.Id == id);
            return View(item);
        }

        [HttpGet("upcoming")]
        public IActionResult Upcoming()
        {
            return View();
        }

        [Authorize]
        [HttpGet("submit")]
        public IActionResult SubmitIco()
        {
            return View();
        }

        [HttpPost("submit")]
        public async Task<IActionResult> SubmitIco(IcoItem model)
        {
            if (!ModelState.IsValid) return View();

            var user = await _userManager.GetUserAsync(User);

            if(user != null)
                model.Customer = user;

            _context.IcoItems.Add(model);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult News()
        {
            return View();
        }
    }
}

TopHundred/Views/IcosList/IcoDetail.cshtml
@model IcoItem
@{
    ViewBag.Title = "Ico Detail";
}


<div class="row" style="margin-top: 100px">
    <div class="col col-6 col-md-2">
        <img src="~/img/mario.jpg" class="img-fluid card" alt="" /><br />
    </div>
    <div class="col col-md-9"><h2 style="color: #2f4f4f;">@Model.Name (@Model.Symbol)</h2></div>
</div>
<div class="row" style="margin-top: 40px;">
    <div class="col col-12 col-md-8">

        <ul class="list-group list-group-flush" >
            <li class="list-group-item"></li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col col-sm-6" style="padding-left: 0;">Status</div>
                    <div class="col col-sm-6" style="font-weight: bold;">@Model.Status</div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col col-sm-6" style="padding-left: 0;">Start Time</div>
                    <div class="col col-sm-6" style="font-weight: bold;">@Model.StartTime</div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col col-sm-6" style="padding-left: 0;">End Time</div>
                    <div class="col col-sm-6" style="font-weight: bold;">@Model.EndTime</div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col col-sm-6" style="padding-left: 0;">Token Count</div>
                    <div class="col col-sm-6" style="font-weight: bold;">@Model.TotalTokenCount.ToString("##,###") @Model.Symbol</div>
        </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col col-sm-6" style="padding-left: 0;">Links</div>
                <div class="col col-sm-6" style="font-weight: bold;">to be filled</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col col-sm-6" style="padding-left: 0;">Whitepaper</div>
                <div class="col col-sm-6" style="font-weight: bold;">@Model.WhitePaper</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col col-sm-6" style="padding-left: 0;">Description</div>
                <div class="col col-sm-6" style="font-weight: bold;">@Model.Description</div>
            </div>
        </li>
        <li class="list-group-item"></li>
        </ul>
    </div>
</div>
<div class="row" style="margin-top: 100px;">
    detailed content
</div>
@*<div class="row">
        <div class="col col-sm-12 col-md-4">
            <i class="material-icons fa fa-pencil fa-2x"></i>
            <span class="title">@Model.ListPosition.PositionValue @Model.Name (@Model.Symbol)</span>
            <a asp-controller="IcosList" asp-action="IcoDetail" asp-route-id="@Model.Id">@Model.Name</a>
        </div>
        <div class="col col-sm-12 col-md-4">
            <i class="material-icons fa fa-pencil fa-2x"></i>
            <span class="title">@Model.ListPosition.PositionValue @Model.Name (@Model.Symbol)</span>
        </div>
        <div class="col col-sm-12 col-md-4">
            <a href="#" class="secondary-content"><i class="material-icons">@Model.StartTime.ToString("dd.MM.yyyy") - @Model.EndTime.ToString("dd.MM.yyyy")</i></a>
        </div>
        <p>
            @Model.Description
        </p>


    </div>*@

TopHundred/Views/IcosList/Index.cshtml
@model IEnumerable<IcoItem>
@{
    ViewBag.Title = "Ico Index";
}

<form class="form-row col-11 col-md-12" style="margin: 15px 0; padding-top: 10px;">
    <div class="offset-md-7 col-md-5 col-8 offset-2">
        <div class="input-group">
            <input type="search" class="form-control" placeholder="Search...">
            <button class="input-group-append btn btn-success" type="submit"><i class="fa fa-search"></i></button>
        </div>
    </div>
</form>

<div class="card-panel" style="margin: 75px 0;">
    <h2 class="text-center text-md-left">TOP TRENDING ICOS</h2>
</div>
<div class="table-responsive">
    <table class="table table-hover" >
        <thead>
            <tr style="font-size: 1.1em;">
                <th></th>
                <th>Rank</th>
                <th>Status</th>
                <th>Price</th>
                <th>Start</th>
                <th>End</th>
                <th class="text-center">Count</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
        <tr>

            <td>

                <a asp-action="IcoDetail" asp-controller="IcosList" asp-route-id="@item.Id" style="color: #000; text-decoration: none;">
                    <img src="~/img/3d.png" class="img-thumbnail responsive-img" style="height: 35px;" /><br />
                    @item.Name (@item.Symbol)
                </a>
            </td>
            <td>@item.Rank</td>
            <td style="color: #000080;">@item.Status</td>
            <td>@item.Price @item.PriceCurrency</td>
            <td>@item.StartTime.ToString("MMM dd, yyyy")</td>
            <td>@item.EndTime.ToString("MMM dd, yyyy")</td>
            <td class="text-center">@item.TotalTokenCount.ToString("##,###") @item.Symbol</td>
        </tr>
        }
        <tr>
            <td></td><td></td><td></td><td></td><td></td><td></td>
        </tr>
    </table>
</div>


@*<div class="row">
        <table class="striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Symblo</th>
                <th>Start Time</th>
                <th>End Time</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><a href="#">@item.Name</a></td>
                    <td>@item.Symbol</td>
                    <td>@item.StartTime</td>
                    <td>@item.EndTime</td>
                </tr>
            }
            </tbody>
        </table>
    </div>*@

TopHundred/Views/IcosList/News.cshtml
@{
    ViewData["Title"] = "ContactUs";
}

<div class="card-panel" style="margin-top: 50px;">
    <h2>News Page coming soon...</h2>
</div>

TopHundred/Views/IcosList/SubmitIco.cshtml
@model IcoItem
@{
    ViewData["Title"] = "Submit an ICO";
}
@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row" style="margin: 60px 0 0 0;">
    <div class="col-12 col-md-10 offset-md-1">
        <div class="modal-header">
            <h2 class="text-center text-md-left" style="margin: 20px 0;">Submit ICO</h2>
        </div>
        <div class="row">
            <div class="card-body">
                <form class="" method="post">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input type="text" class="form-control" asp-for="Name" placeholder="ICO name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Icon">Icon</label>
                        <input type="text" class="form-control" asp-for="Icon" placeholder="Icon link">
                        <span asp-validation-for="Icon" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Symbol">Symbol</label>
                        <input type="text" class="form-control" asp-for="Symbol" placeholder="ICO Symbol">
                        <span asp-validation-for="Symbol" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status">Status</label>
                        <select class="form-control" asp-for="Status">
                            <option>Active</option>
                            <option>TBD</option>
                            <option>Sold Out</option>
                        </select>
                        <span asp-validation-for="Status"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price">Price</label>
                        <div class="col-6">
                            <div class="row">

                                <div class="col-6" style="padding-left: 0;">
                                    <input type="number" class="form-control" asp-for="Price" placeholder="ICO Price">
                                </div>
                                <div class="col-6" style="padding-left: 0;">
                                    <select class="form-control" asp-for="PriceCurrency">
                                        <option>BTC</option>
                                        <option>BCH</option>
                                        <option>ETH</option>
                                    </select>
                                </div>
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>                        
                    </div>
                    <div class="form-group">
                        <label asp-for="StartTime">Start Time</label>
                        <input class="form-control" type="date" asp-for="StartTime" />
                        <span asp-validation-for="StartTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EndTime">End Time</label>
                        <input class="form-control" type="date" asp-for="EndTime" />
                        <span asp-validation-for="EndTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WhitePaper">Whitepaper link</label>
                        <input type="text" class="form-control" asp-for="WhitePaper" placeholder="Whitepaper link">
                        <span asp-validation-for="WhitePaper" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TotalTokenCount">Total token count</label>
                        <input type="text" class="form-control" asp-for="TotalTokenCount" placeholder="Total token count">
                        <span asp-validation-for="TotalTokenCount" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description">Description</label>
                        <textarea type="text" class="form-control" asp-for="Description" placeholder="ICO description" rows="3"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-dark btn-block col-12 col-sm-3">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>